
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.BanamexEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : Banamex entity
    /// File                    : BanamexEntity.cs
    /// Creation date           : 19/07/2017
    /// Creation time           : 11:31 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class BanamDatosMerchantEntity 
    {
        #region Attributes


        /// <summary>
        /// Property merchantId
        /// </summary>
        [DataMember]
        public String merchantId { get; set; }
        /// <summary>
        /// Property userId
        /// </summary>
        [DataMember]
        public String userId { get; set; }
        /// <summary>
        /// Property password
        /// </summary>
        [DataMember]
        public String password { get; set; }

        /// <summary>
        /// Property merchantName
        /// </summary>
        [DataMember]
        public String merchantName { get; set; }
        /// <summary>
        /// Property addressLine1
        /// </summary>
        [DataMember]
        public String addressLine1 { get; set; }
        /// <summary>
        /// Property addressLine2
        /// </summary>
        [DataMember]
        public String addressLine2 { get; set; }

        /// <summary>
        /// Property email
        /// </summary>
        [DataMember]
        public String email { get; set; }

        /// <summary>
        /// Property descripcionImporte
        /// </summary>
        [DataMember]
        public String descripcionImporte { get; set; }


        /// <summary>
        /// Property cancelUrl
        /// </summary>
        [DataMember]
        public String cancelUrl { get; set; }


        /// <summary>
        /// Property returnUrl
        /// </summary>
        [DataMember]
        public String returnUrl { get; set; }



        /// <summary>
        /// Property cancelUrl
        /// </summary>
        [DataMember]
        public int? timeoutSeg { get; set; }


        /// <summary>
        /// Property cancelUrl
        /// </summary>
        [DataMember]
        public String timeoutUrl { get; set; }
        
        #endregion
    }
}

