
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.BanamexEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : Banamex entity
    /// File                    : BanamexEntity.cs
    /// Creation date           : 19/07/2017
    /// Creation time           : 11:31 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class BanamexSessionBancoEntity 
    {
        #region Attributes

        /// <summary>
        /// Property clv_session
        /// </summary>
        [DataMember]
        public long? clv_session { get; set; }

        /// <summary>
        /// Property successIndicator
        /// </summary>
        [DataMember]
        public String idSession { get; set; }

        
        
        #endregion
    }
}

