
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.ChecaOrdenRetiroEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : ChecaOrdenRetiro entity
    /// File                    : ChecaOrdenRetiroEntity.cs
    /// Creation date           : 20/01/2017
    /// Creation time           : 12:31 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class ChecaOrdenRetiroEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Resultado
        /// </summary>
        [DataMember]
        public int? Resultado { get; set; }
        /// <summary>
        /// Property Msg
        /// </summary>
        [DataMember]
        public String Msg { get; set; }




        [DataMember]
        public long? Contrato { get; set; }


        #endregion
    }
}

