
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.DameSerDelCliFacEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : DameSerDelCliFac entity
    /// File                    : DameSerDelCliFacEntity.cs
    /// Creation date           : 14/10/2016
    /// Creation time           : 11:14 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class DameSerDelCliFacEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Servicio
        /// </summary>
        /// 

        [DataMember]
        public long? Contrato { get; set; }



        [DataMember]
        public String Servicio { get; set; }
        #endregion
    }
}

