
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.DameClv_SessionEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : DameClv_Session entity
    /// File                    : DameClv_SessionEntity.cs
    /// Creation date           : 13/10/2016
    /// Creation time           : 06:46 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class DameClv_SessionEntity 
    {
        #region Attributes

        /// <summary>
        /// Property IdSession
        /// </summary>
        [DataMember]
        public long? Clv_Session { get; set; }


        [DataMember]
        public int? Error { get; set; }

        [DataMember]
        public String Msg { get; set; }


        #endregion
    }
}

