
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.GrabaFacturas2Entity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : GrabaFacturas2 entity
    /// File                    : GrabaFacturas2Entity.cs
    /// Creation date           : 28/10/2016
    /// Creation time           : 06:06 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class GrabaFacturas2Entity 
    {
        #region Attributes

        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property Clv_Session
        /// </summary>
        [DataMember]
        public long? Clv_Session { get; set; }
        /// <summary>
        /// Property Cajera
        /// </summary>
        [DataMember]
        public String Cajera { get; set; }
        /// <summary>
        /// Property Sucursal
        /// </summary>
        [DataMember]
        public int? Sucursal { get; set; }
        /// <summary>
        /// Property Tipo
        /// </summary>
        [DataMember]
        public String Tipo { get; set; }
        /// <summary>
        /// Property Serie_V
        /// </summary>
        [DataMember]
        public String Serie_V { get; set; }
        /// <summary>
        /// Property Folio_V
        /// </summary>
        [DataMember]
        public long? Folio_V { get; set; }
        /// <summary>
        /// Property Clv_Vendedor
        /// </summary>
        [DataMember]
        public int? Clv_Vendedor { get; set; }
        /// <summary>
        /// Property Tipo1
        /// </summary>
        [DataMember]
        public int? Tipo1 { get; set; }
        /// <summary>
        /// Property Monto1
        /// </summary>
        [DataMember]
        public Decimal? Monto1 { get; set; }
        /// <summary>
        /// Property GLOEFECTIVO2
        /// </summary>
        [DataMember]
        public Decimal? GLOEFECTIVO2 { get; set; }
        /// <summary>
        /// Property GLOCHEQUE2
        /// </summary>
        [DataMember]
        public Decimal? GLOCHEQUE2 { get; set; }
        /// <summary>
        /// Property GLOCLV_BANCOCHEQUE2
        /// </summary>
        [DataMember]
        public int? GLOCLV_BANCOCHEQUE2 { get; set; }
        /// <summary>
        /// Property NUMEROCHEQUE2
        /// </summary>
        [DataMember]
        public String NUMEROCHEQUE2 { get; set; }
        /// <summary>
        /// Property GLOTARJETA2
        /// </summary>
        [DataMember]
        public Decimal? GLOTARJETA2 { get; set; }
        /// <summary>
        /// Property GLOCLV_BANCOTARJETA2
        /// </summary>
        [DataMember]
        public int? GLOCLV_BANCOTARJETA2 { get; set; }
        /// <summary>
        /// Property NUMEROTARJETA2
        /// </summary>
        [DataMember]
        public String NUMEROTARJETA2 { get; set; }
        /// <summary>
        /// Property TARJETAAUTORIZACION2
        /// </summary>
        [DataMember]
        public String TARJETAAUTORIZACION2 { get; set; }
        /// <summary>
        /// Property CLV_Nota3
        /// </summary>
        [DataMember]
        public long? CLV_Nota3 { get; set; }
        /// <summary>
        /// Property GLONOTA3
        /// </summary>
        [DataMember]
        public Decimal? GLONOTA3 { get; set; }
        /// <summary>
        /// Property BndError
        /// </summary>
        [DataMember]
        public int? BndError { get; set; }
        /// <summary>
        /// Property Msg
        /// </summary>
        [DataMember]
        public String Msg { get; set; }
        /// <summary>
        /// Property Clv_FacturaSalida
        /// </summary>
        [DataMember]
        public long? Clv_FacturaSalida { get; set; }




        [DataMember]
        public String IpMaquina { get; set; }



        [DataMember]
        public String Token { get; set; }



        #endregion
    }
}

