
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.InformacionClientePeriodosEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : InformacionClientePeriodos entity
    /// File                    : InformacionClientePeriodosEntity.cs
    /// Creation date           : 22/10/2016
    /// Creation time           : 09:45 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class InformacionClientePeriodosEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Periodo
        /// </summary>
        /// 

        [DataMember]
        public long? Contrato { get; set; }



        [DataMember]
        public String Periodo { get; set; }
        /// <summary>
        /// Property Puntos
        /// </summary>
        [DataMember]
        public String Puntos { get; set; }
        /// <summary>
        /// Property Alta
        /// </summary>
        [DataMember]
        public String Alta { get; set; }
        /// <summary>
        /// Property Corte
        /// </summary>
        [DataMember]
        public String Corte { get; set; }
        /// <summary>
        /// Property Periodo1
        /// </summary>
        [DataMember]
        public String Periodo1 { get; set; }
        /// <summary>
        /// Property Periodofin
        /// </summary>
        [DataMember]
        public String Periodofin { get; set; }




        [DataMember]
        public int? Resultado { get; set; }


        #endregion
    }
}

