
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.ObtieneEdoCuentaSinSaldarEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : ObtieneEdoCuentaSinSaldar entity
    /// File                    : ObtieneEdoCuentaSinSaldarEntity.cs
    /// Creation date           : 03/03/2017
    /// Creation time           : 01:25 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class ObtieneEdoCuentaSinSaldarEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property ClvSession
        /// </summary>
        [DataMember]
        public long? ClvSession { get; set; }



        [DataMember]
        public long? IdEstadoCuenta { get; set; }

        [DataMember]
        public String Fecha { get; set; }

        [DataMember]
        public decimal? TotalRegular { get; set; }




        #endregion
    }
}

