
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.SequenceIdEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : SequenceId entity
    /// File                    : SequenceIdEntity.cs
    /// Creation date           : 01/03/2017
    /// Creation time           : 10:11 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class SequenceIdEntity 
    {
        #region Attributes

        /// <summary>
        /// Property SequenceId
        /// </summary>
        [DataMember]
        public long? SequenceId { get; set; }



        [DataMember]
        public String TransactionSequenceId { get; set; }
               


        #endregion
    }
}

