
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.SumaDetalleEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : SumaDetalle entity
    /// File                    : SumaDetalleEntity.cs
    /// Creation date           : 14/10/2016
    /// Creation time           : 11:32 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class SumaDetalleEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Clv_Session
        /// </summary>
        [DataMember]
        public int? Clv_Session { get; set; }
        /// <summary>
        /// Property Posicion
        /// </summary>
        [DataMember]
        public int? Posicion { get; set; }
        /// <summary>
        /// Property Nivel
        /// </summary>
        [DataMember]
        public int? Nivel { get; set; }
        /// <summary>
        /// Property Descripcion
        /// </summary>
        [DataMember]
        public String Descripcion { get; set; }
        /// <summary>
        /// Property Total
        /// </summary>
        [DataMember]
        public Decimal? Total { get; set; }
        #endregion
    }


    public class importeTotalEntity 
    {
        #region Attributes

        [DataMember]
        public String Descripcion { get; set; }
        /// <summary>
        /// Property Total
        /// </summary>
        [DataMember]
        public Decimal? Total { get; set; }

        #endregion
    }

}

