
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.tieneEdoCuentaEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : tieneEdoCuenta entity
    /// File                    : tieneEdoCuentaEntity.cs
    /// Creation date           : 28/02/2017
    /// Creation time           : 05:16 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class tieneEdoCuentaEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property tieneEdoCuenta
        /// </summary>
        [DataMember]
        public bool tieneEdoCuenta { get; set; }
        /// <summary>
        /// Property idEstadoCuenta
        /// </summary>
        [DataMember]
        public long? idEstadoCuenta { get; set; }
        #endregion
    }
}

