
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.TipoContactoEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : TipoContacto entity
    /// File                    : TipoContactoEntity.cs
    /// Creation date           : 23/02/2017
    /// Creation time           : 04:28 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class TipoContactoEntity 
    {
    #region Attributes
    
      /// <summary>
      /// Property IdTipoContacto
      /// </summary>
      [DataMember]
      public long? IdTipoContacto { get; set; }
      /// <summary>
      /// Property Nombre
      /// </summary>
      [DataMember]
      public String Nombre { get; set; }
    #endregion
    }
    }

  