
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.uspHaz_PreguntaEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : uspHaz_Pregunta entity
    /// File                    : uspHaz_PreguntaEntity.cs
    /// Creation date           : 19/01/2017
    /// Creation time           : 06:40 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class uspHaz_PreguntaEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Pregunta
        /// </summary>
        [DataMember]
        public String Pregunta { get; set; }
        /// <summary>
        /// Property MesesAdelantados
        /// </summary>
        [DataMember]
        public int? MesesAdelantados { get; set; }


        [DataMember]
        public int? Op { get; set; }

        [DataMember]
        public long? Contrato { get; set; }


        [DataMember]
        public long? ClvSession { get; set; }


        [DataMember]
        public int? Error { get; set; }

        [DataMember]
        public String Msg { get; set; }

        [DataMember]
        public int? Op2 { get; set; }


        #endregion
    }
}

