
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.CobraSaldoEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : CobraSaldo entity
    /// File                    : CobraSaldoEntity.cs
    /// Creation date           : 03/03/2017
    /// Creation time           : 01:16 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class ValidaContratoNoMaestroEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public int? PerteneceMaestro { get; set; }
     

        #endregion
    }
}

