
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.BanamexEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : Banamex entity
    /// File                    : BanamexEntity.cs
    /// Creation date           : 19/07/2017
    /// Creation time           : 11:31 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class BanamexGuardaPagoEntity 
    {
        #region Attributes

        /// <summary>
        /// Property BndError
        /// </summary>
        [DataMember]
        public int? BndError { get; set; }

        /// <summary>
        /// Property MsgError
        /// </summary>
        [DataMember]
        public String MsgError { get; set; }

        /// <summary>
        /// Property clv_Session
        /// </summary>
        [DataMember]

        public long? clv_Session { get; set; }

        /// <summary>
        /// Property contrato
        /// </summary>
        [DataMember]
        public long? contrato { get; set; }



        #endregion
    }
}

