
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.BusCliPorContrato_FacEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : BusCliPorContrato_Fac entity
    /// File                    : BusCliPorContrato_FacEntity.cs
    /// Creation date           : 13/10/2016
    /// Creation time           : 06:52 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class BusCliPorContrato_FacEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Id
        /// </summary>
        //[DataMember]
        //public int? Id { get; set; }
        /// <summary>
        /// Property Contrato
        /// </summary>
        /// 
        [DataMember]
        public String ContratoC { get; set; }


        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property Nombre
        /// </summary>
        [DataMember]
        public String Nombre { get; set; }
        /// <summary>
        /// Property Calle
        /// </summary>
        [DataMember]
        public String Calle { get; set; }
        /// <summary>
        /// Property Colonia
        /// </summary>
        [DataMember]
        public String Colonia { get; set; }
        /// <summary>
        /// Property Numero
        /// </summary>
        [DataMember]
        public String Numero { get; set; }
        /// <summary>
        /// Property Ciudad
        /// </summary>
        [DataMember]
        public String Ciudad { get; set; }
        /// <summary>
        /// Property SoloInternet
        /// </summary>
        [DataMember]
        public bool? SoloInternet { get; set; }
        /// <summary>
        /// Property EsHotel
        /// </summary>
        [DataMember]
        public bool? EsHotel { get; set; }
        /// <summary>
        /// Property Telefono
        /// </summary>
        [DataMember]
        public String Telefono { get; set; }
        /// <summary>
        /// Property Celular
        /// </summary>
        [DataMember]
        public String Celular { get; set; }
        /// <summary>
        /// Property DesglosaIVA
        /// </summary>
        [DataMember]
        public bool? Desglosa_IVA { get; set; }



        [DataMember]
        public int? Id { get; set; }


        [DataMember]
        public String ContratoCom { get; set; }

        #endregion
    }
}

