
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.ContratoMaestroFacEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : ContratoMaestroFac entity
    /// File                    : ContratoMaestroFacEntity.cs
    /// Creation date           : 22/02/2017
    /// Creation time           : 10:49 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class ContratoMaestroFacEntity 
    {
        #region Attributes

        /// <summary>
        /// Property IdContratoMaestro
        /// </summary>
        [DataMember]
        public long? IdContratoMaestro { get; set; }
        /// <summary>
        /// Property RazonSocial
        /// </summary>
        [DataMember]
        public String RazonSocial { get; set; }
        /// <summary>
        /// Property NombreComercial
        /// </summary>
        [DataMember]
        public String NombreComercial { get; set; }
        /// <summary>
        /// Property Distribuidor
        /// </summary>
        [DataMember]
        public int? Distribuidor { get; set; }
        /// <summary>
        /// Property Calle
        /// </summary>
        [DataMember]
        public int? Calle { get; set; }
        /// <summary>
        /// Property NumExt
        /// </summary>
        [DataMember]
        public String NumExt { get; set; }
        /// <summary>
        /// Property NumInt
        /// </summary>
        [DataMember]
        public String NumInt { get; set; }
        /// <summary>
        /// Property Ciudad
        /// </summary>
        [DataMember]
        public int? Ciudad { get; set; }
        /// <summary>
        /// Property Estado
        /// </summary>
        [DataMember]
        public int? Estado { get; set; }
        /// <summary>
        /// Property CodigoPostal
        /// </summary>
        [DataMember]
        public String CodigoPostal { get; set; }
        /// <summary>
        /// Property RFC
        /// </summary>
        [DataMember]
        public String RFC { get; set; }
        /// <summary>
        /// Property Prepago
        /// </summary>
        [DataMember]
        public bool? Prepago { get; set; }
        /// <summary>
        /// Property PostPago
        /// </summary>
        [DataMember]
        public bool? PostPago { get; set; }
        /// <summary>
        /// Property DiasCredito
        /// </summary>
        [DataMember]
        public int? DiasCredito { get; set; }
        /// <summary>
        /// Property DiasGracia
        /// </summary>
        [DataMember]
        public int? DiasGracia { get; set; }
        /// <summary>
        /// Property LimiteCredito
        /// </summary>
        [DataMember]
        public int? LimiteCredito { get; set; }
        /// <summary>
        /// Property FechaFac
        /// </summary>
        [DataMember]
        public String FechaFac { get; set; }
        /// <summary>
        /// Property PagoEdoCuetna
        /// </summary>
        [DataMember]
        public bool? PagoEdoCuetna { get; set; }
        /// <summary>
        /// Property PagoFac
        /// </summary>
        [DataMember]
        public bool? PagoFac { get; set; }
        /// <summary>
        /// Property TipoCorteCli
        /// </summary>
        [DataMember]
        public int? TipoCorteCli { get; set; }
        /// <summary>
        /// Property ReactivarMan
        /// </summary>
        [DataMember]
        public bool? ReactivarMan { get; set; }
        /// <summary>
        /// Property ReactivarPagoFac
        /// </summary>
        [DataMember]
        public bool? ReactivarPagoFac { get; set; }
        /// <summary>
        /// Property TipoPago
        /// </summary>
        [DataMember]
        public int? TipoPago { get; set; }








        [DataMember]
        public int? Localidad { get; set; }


        [DataMember]
        public int? Colonia { get; set; }


        [DataMember]
        public int? ClvCiudad { get; set; }
        

        [DataMember]
        public int? Op { get; set; }





        [DataMember]
        public String DistribuidorDes { get; set; }

        [DataMember]
        public String EstadoDes { get; set; }

        [DataMember]
        public String CiudadDes { get; set; }

        [DataMember]
        public String LocalidadDes { get; set; }

        [DataMember]
        public String ColoniaDes { get; set; }

        [DataMember]
        public String CalleDes { get; set; }

        [DataMember]
        public long? ContratoReal { get; set; }

        [DataMember]
        public String ContratoCom { get; set; }

        [DataMember]
        public String NombreCli { get; set; }

        [DataMember]
        public String Direccion { get; set; }

        [DataMember]
        public String Contrato { get; set; }


        [DataMember]
        public String Referencia { get; set; }


        [DataMember]
        public String Referencia2 { get; set; }


        [DataMember]
        public int? ClvBanco { get; set; }










        [DataMember]
        public List<RelContratoMaestro_ContratoSoftvEntity> lstRel { get; set; }


        [DataMember]
        public List<DatosClienteSoftv> lstCliS { get; set; }


        [DataMember]
        public List<ContratoMaestroFacEntity> Contratos { get; set; }



        [DataMember]
        public int? Error { get; set; }

        [DataMember]
        public String Msg { get; set; }


        [DataMember]
        public int? Bandera { get; set; }




        [DataMember]
        public int? Nivel { get; set; }

        [DataMember]
        public bool? Proporcional { get; set; }



        #endregion
    }


    public class LayOutFacEntity
    {
        public List<DetLayOutFac> ContratosValidos { get; set; }

        public List<DetLayOutFac> ContratosNoValidos { get; set; }
    }

    public class DetLayOutFac{
        public string ContratoReal{get; set;}
        public string ContratoCom {get; set;}

        public string Referencia{get; set;}
        public string Nombre { get; set; }

        public int Nivel { get; set; }

        public bool Proporcional { get; set; }
    }


}

