
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.DameDetalleEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : DameDetalle entity
    /// File                    : DameDetalleEntity.cs
    /// Creation date           : 14/10/2016
    /// Creation time           : 11:29 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class DameDetalleEntity 
    {
        #region Attributes

        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property Clv_Session
        /// </summary>
        [DataMember]
        public long? Clv_Session { get; set; }
        /// <summary>
        /// Property CLV_SERVICIO
        /// </summary>
        [DataMember]
        public int? CLV_SERVICIO { get; set; }
        /// <summary>
        /// Property Clv_llavedelservicio
        /// </summary>
        [DataMember]
        public int? Clv_llavedelservicio { get; set; }
        /// <summary>
        /// Property Clv_UnicaNet
        /// </summary>
        [DataMember]
        public long? Clv_UnicaNet { get; set; }
        /// <summary>
        /// Property CLAVE
        /// </summary>
        [DataMember]
        public int? CLAVE { get; set; }
        /// <summary>
        /// Property Pagos_Adelantados
        /// </summary>
        [DataMember]
        public String Pagos_Adelantados { get; set; }
        /// <summary>
        /// Property tvAdic
        /// </summary>
        [DataMember]
        public int? tvAdic { get; set; }
        /// <summary>
        /// Property Meses_Cortesia
        /// </summary>
        [DataMember]
        public int? Meses_Cortesia { get; set; }
        /// <summary>
        /// Property mesesApagar
        /// </summary>
        [DataMember]
        public int? mesesApagar { get; set; }
        /// <summary>
        /// Property importe
        /// </summary>
        [DataMember]
        public Decimal? importe { get; set; }
        /// <summary>
        /// Property periodoPagadoIni
        /// </summary>
        [DataMember]
        public String periodoPagadoIni { get; set; }
        /// <summary>
        /// Property periodoPagadoFin
        /// </summary>
        [DataMember]
        public String periodoPagadoFin { get; set; }
        /// <summary>
        /// Property PuntosAplicadosOtros
        /// </summary>
        [DataMember]
        public int? PuntosAplicadosOtros { get; set; }
        /// <summary>
        /// Property puntosAplicadosAnt
        /// </summary>
        [DataMember]
        public int? puntosAplicadosAnt { get; set; }
        /// <summary>
        /// Property PuntosAplicadosPagoAdelantado
        /// </summary>
        [DataMember]
        public int? PuntosAplicadosPagoAdelantado { get; set; }
        /// <summary>
        /// Property DescuentoNet
        /// </summary>
        [DataMember]
        public Decimal? DescuentoNet { get; set; }
        /// <summary>
        /// Property Des_Otr_Ser_Misma_Categoria
        /// </summary>
        [DataMember]
        public Decimal? Des_Otr_Ser_Misma_Categoria { get; set; }
        /// <summary>
        /// Property bonificacion
        /// </summary>
        [DataMember]
        public Decimal? bonificacion { get; set; }
        /// <summary>
        /// Property importeAdicional
        /// </summary>
        [DataMember]
        public Decimal? importeAdicional { get; set; }
        /// <summary>
        /// Property columnaDetalle
        /// </summary>
        [DataMember]
        public String columnaDetalle { get; set; }
        /// <summary>
        /// Property DiasBonifica
        /// </summary>
        [DataMember]
        public int? DiasBonifica { get; set; }
        /// <summary>
        /// Property mesesBonificar
        /// </summary>
        [DataMember]
        public int? mesesBonificar { get; set; }
        /// <summary>
        /// Property importeBonifica
        /// </summary>
        [DataMember]
        public Decimal? importeBonifica { get; set; }
        /// <summary>
        /// Property Ultimo_Mes
        /// </summary>
        [DataMember]
        public int? Ultimo_Mes { get; set; }
        /// <summary>
        /// Property Ultimo_anio
        /// </summary>
        [DataMember]
        public int? Ultimo_anio { get; set; }
        /// <summary>
        /// Property Adelantado
        /// </summary>
        [DataMember]
        public bool? Adelantado { get; set; }
        /// <summary>
        /// Property DESCRIPCION
        /// </summary>
        [DataMember]
        public String DESCRIPCION { get; set; }
        /// <summary>
        /// Property MacCableModem
        /// </summary>
        [DataMember]
        public String MacCableModem { get; set; }
        /// <summary>
        /// Property CLV_DETALLE
        /// </summary>
        [DataMember]
        public long? CLV_DETALLE { get; set; }

        /// <summary>
        /// Property DESCORTA
        /// </summary>
        [DataMember]
        public String DESCORTA { get; set; }

        [DataMember]
        public long? CLV_TipSer { get; set; }

        #endregion
    }
}

