
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.DameTiposClientesEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : DameTiposClientes entity
    /// File                    : DameTiposClientesEntity.cs
    /// Creation date           : 14/10/2016
    /// Creation time           : 11:17 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class DameTiposClientesEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Clv_TipoCliente
        /// </summary>
        /// 

        [DataMember]
        public long? Contrato { get; set; }



        [DataMember]
        public int? Clv_TipoCliente { get; set; }
        /// <summary>
        /// Property Descripcion
        /// </summary>
        [DataMember]
        public String Descripcion { get; set; }
        #endregion
    }
}

