
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.ContratoMaestroFacEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : ContratoMaestroFac entity
    /// File                    : ContratoMaestroFacEntity.cs
    /// Creation date           : 22/02/2017
    /// Creation time           : 10:49 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class ServiciosClienteEntity
    {
        [DataMember]
        public String Nombre { get; set; }

        [DataMember]
        public String status { get; set; }
        [DataMember]
        public int Clv_TipSer { get; set; }
    }

    [DataContract]
    [Serializable]
    public class ParametrosOpenPayEntity
    {
        [DataMember]
        public String ID { get; set; }

        [DataMember]
        public String LlavePrivada { get; set; }
        [DataMember]
        public String LlavePublica { get; set; }
        [DataMember]
        public String URL { get; set; }
    }

    [DataContract]
    [Serializable]
    public class ParametrosPagoRedireccionEntity
    {
        [DataMember]
        public String urlRedireccion { get; set; }
        [DataMember]
        public String urlBarcode { get; set; }
        [DataMember]
        public String Reference { get; set; }
        [DataMember]
        public String FechaPago { get; set; }
        [DataMember]
        public String urlRecibo { get; set; }
    }

    [DataContract]
    [Serializable]
    public class Ecom_ContCompEntity 
    {
        #region Attributes

        [DataMember]
        public String ContratoCompuesto { get; set; }

        [DataMember]
        public String Nombre { get; set; }


        [DataMember]
        public long? Contrato { get; set; }

        [DataMember]
        public String Email { get; set; }

        [DataMember]
        public String Telefono { get; set; }

        [DataMember]
        public String Direccion { get; set; }
        [DataMember]
        public String Colonia { get; set; }
        [DataMember]
        public String Ciudad { get; set; }
        [DataMember]
        public List<ServiciosClienteEntity> Servicios { get; set; }
        #endregion
    }

    [DataContract]
    [Serializable]
    public class DatosClienteEntity
    {
        #region Attributes

        [DataMember]
        public String ContratoCompuesto { get; set; }

        [DataMember]
        public String SoloNombre { get; set; }

        [DataMember]
        public String SoloApellidos { get; set; }


        [DataMember]
        public long Contrato { get; set; }

        [DataMember]
        public String Email { get; set; }

        [DataMember]
        public String Telefono { get; set; }

        [DataMember]
        public String Direccion { get; set; }
        [DataMember]
        public String Colonia { get; set; }
        [DataMember]
        public String Ciudad { get; set; }
        #endregion
    }

    [DataContract]
    [Serializable]
    public class DatosFechasPago
    {
        #region Attributes

        [DataMember]
        public String Periodos { get; set; }

        [DataMember]
        public String Puntos { get; set; }

        [DataMember]
        public String Alta { get; set; }

        [DataMember]
        public String Corte { get; set; }

        [DataMember]
        public String Periodo1 { get; set; }

        [DataMember]
        public String PeriodoFin { get; set; }
        #endregion
    }
}

