
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.ContratoMaestroFacEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : ContratoMaestroFac entity
    /// File                    : ContratoMaestroFacEntity.cs
    /// Creation date           : 22/02/2017
    /// Creation time           : 10:49 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class Ecom_CorreoEntity 
    {
        #region Attributes

        /// <summary>
        /// Property ContratoCompuesto
        /// </summary>
        [DataMember]
        public String Correo { get; set; }


        [DataMember]
        public int EsValido { get; set; }

        #endregion
    }

     

}

