
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.PagoAdelantadoEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : PagoAdelantado entity
    /// File                    : PagoAdelantadoEntity.cs
    /// Creation date           : 28/10/2016
    /// Creation time           : 01:03 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class PagoAdelantadoEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Clv_Session
        /// </summary>
        [DataMember]
        public long? Clv_Session { get; set; }
        /// <summary>
        /// Property Clv_Servicio
        /// </summary>
        [DataMember]
        public long? Clv_Servicio { get; set; }
        /// <summary>
        /// Property Clv_llave
        /// </summary>
        [DataMember]
        public long? Clv_llave { get; set; }
        /// <summary>
        /// Property Clv_UnicaNet
        /// </summary>
        [DataMember]
        public long? Clv_UnicaNet { get; set; }
        /// <summary>
        /// Property Clave
        /// </summary>
        [DataMember]
        public int? Clave { get; set; }
        /// <summary>
        /// Property MesesAdelantados
        /// </summary>
        [DataMember]
        public int? MesesAdelantados { get; set; }
        /// <summary>
        /// Property IdTipoCli
        /// </summary>
        [DataMember]
        public int? IdTipoCli { get; set; }
        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property Error
        /// </summary>
        [DataMember]
        public int? Error { get; set; }
        /// <summary>
        /// Property Msg
        /// </summary>
        [DataMember]
        public String Msg { get; set; }


        [DataMember]
        public int? max { get; set; }

        [DataMember]
        public int? numeroAdelantar { get; set; }



        #endregion
    }
}

