
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.Reporte_TokensEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : Reporte_Tokens entity
    /// File                    : Reporte_TokensEntity.cs
    /// Creation date           : 09/03/2017
    /// Creation time           : 03:21 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class Reporte_TokensEntity 
    {
    #region Attributes
    
      /// <summary>
      /// Property Beam
      /// </summary>
      [DataMember]
      public int? Beam { get; set; }

      /// <summary>
      /// Property SatellitedID
      /// </summary>
      [DataMember]
      public String SatellitedID { get; set; }
  
      /// <summary>
      /// Property Suscriptor
      /// </summary>
      [DataMember]
      public String Suscriptor { get; set; }
      /// <summary>
      /// Property SAN
      /// </summary>
      [DataMember]
      public long? SAN { get; set; }
      /// <summary>
      /// Property PlanServ
      /// </summary>
      [DataMember]
      public String PlanServ { get; set; }
      /// <summary>
      /// Property ESN
      /// </summary>
      [DataMember]
      public String ESN { get; set; }
      /// <summary>
      /// Property Detalle1
      /// </summary>
      [DataMember]
      public String Detalle1 { get; set; }
      /// <summary>
      /// Property FechaIngreso
      /// </summary>
      [DataMember]
      public String FechaIngreso { get; set; }
      /// <summary>
      /// Property Latitud
      /// </summary>
      [DataMember]
      public String Latitud { get; set; }
      /// <summary>
      /// Property Longitud
      /// </summary>
      [DataMember]
      public String Longitud { get; set; }
      /// <summary>
      /// Property FechaAlta
      /// </summary>
      [DataMember]
      public String FechaAlta { get; set; }
      /// <summary>
      /// Property Usuario
      /// </summary>
      [DataMember]
      public String Usuario { get; set; }

 

    #endregion
    }
    }

  