
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.SeguridadTokenEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : SeguridadToken entity
    /// File                    : SeguridadTokenEntity.cs
    /// Creation date           : 17/11/2016
    /// Creation time           : 09:30 a. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class SeguridadTokenEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Token1
        /// </summary>
        [DataMember]
        public String Token1 { get; set; }
        /// <summary>
        /// Property Token2
        /// </summary>
        [DataMember]
        public String Token2 { get; set; }
        /// <summary>
        /// Property IdUsuario
        /// </summary>
        [DataMember]
        public int? IdUsuario { get; set; }
        /// <summary>
        /// Property Usuario
        /// </summary>
        [DataMember]
        public String Usuario { get; set; }
        /// <summary>
        /// Property IdSucursal
        /// </summary>
        [DataMember]
        public int? IdSucursal { get; set; }
        /// <summary>
        /// Property IpMaquina
        /// </summary>
        [DataMember]
        public String IpMaquina { get; set; }
        /// <summary>
        /// Property ClvSession
        /// </summary>
        [DataMember]
        public long? ClvSession { get; set; }
        #endregion
    }
}

