
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.sp_dameContratoCompaniaAdicEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : sp_dameContratoCompaniaAdic entity
    /// File                    : sp_dameContratoCompaniaAdicEntity.cs
    /// Creation date           : 30/01/2017
    /// Creation time           : 06:45 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class sp_dameContratoCompaniaAdicEntity 
    {
        #region Attributes

        /// <summary>
        /// Property ContratoCom
        /// </summary>
        [DataMember]
        public String ContratoCom { get; set; }
        /// <summary>
        /// Property ClvUsuario
        /// </summary>
        [DataMember]
        public int? ClvUsuario { get; set; }
        /// <summary>
        /// Property Modulo
        /// </summary>
        [DataMember]
        public String Modulo { get; set; }
        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public long? Contrato { get; set; }
        #endregion
    }
}

