
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.TipoUsuarioEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : TipoUsuario entity
    /// File                    : TipoUsuarioEntity.cs
    /// Creation date           : 18/02/2017
    /// Creation time           : 01:29 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class TipoUsuarioEntity
    {
        #region Attributes

        /// <summary>
        /// Property IdTipoUsuario
        /// </summary>
        [DataMember]
        public int? IdTipoUsuario { get; set; }
        /// <summary>
        /// Property Nombre
        /// </summary>
        [DataMember]
        public String Nombre { get; set; }
        [DataMember]
        public UsuarioSystemEntity UsuarioSystem { get; set; }

        #endregion
    }
}

