
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace SoftvWCFService.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.ValidaSaldoContratoEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : ValidaSaldoContrato entity
    /// File                    : ValidaSaldoContratoEntity.cs
    /// Creation date           : 03/03/2017
    /// Creation time           : 12:59 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class ValidaSaldoContratoEntity 
    {
        #region Attributes

        /// <summary>
        /// Property Contrato
        /// </summary>
        [DataMember]
        public long? Contrato { get; set; }
        /// <summary>
        /// Property tieneSaldo
        /// </summary>
        [DataMember]
        public int? tieneSaldo { get; set; }
        #endregion
    }
}

